### ISSUE TITLE
server management help

### ISSUE THREAD

**Issue by LinusAWZZL** [JohnWhy/DnD-Discord-Bot#11]
when managing a server with people, i find it hard to monitor people's characters
im thinking maybe
!servercharlist (showing the list of characters on a server)
!charinfo @... (showing the characters of that person)
and maybe allow using @... to target people
i.e. !set xp @... 500

other than that awesome bot, thanks ^-^

**Comment by JohnWhy** [comment]
Known enhancements which will be coming with DMTools update (eventually)
