### ISSUE TITLE
Strange things going on with High Elf/Rogue Proficiencies.

### ISSUE THREAD

**Issue by jdougharty** [JohnWhy/DnD-Discord-Bot#13]
Hey folks, just made a high elf rogue using the PHB, then used the bot to make him. I've hit generating the proficiencies and it's not listing Investigation as selection (despite this being an available choice via phb for Rogues) and it's offering Perception (despite this being given automatically by Elf Racial via PHB).

**Comment by JohnWhy** [comment]
Fixed
