### ISSUE TITLE
Floating negative modifiers

### ISSUE THREAD

**Issue by boo9nine** [JohnWhy/DnD-Discord-Bot#14]
To add a negative floating modifier to a roll, you currently need to "add a negative number". If you attempt to directly subtract the modifier, the bot will instead add the modifier.
(input !r1d20 -5 may return sum 11+5=16, instead of 11-5=6, as you would expect. To get the desired output, you need to specify with +-5, which will output sum 11-5=6,
This is unintuitive, and could be improved by making the bot correctly interpret - as subtract.

**Comment by JohnWhy** [comment]
Will be fixed

**Comment by JohnWhy** [comment]
Apologies for leaving this open, this is fixed for a while.  Closing ticket.

![image](https://user-images.githubusercontent.com/8998268/82575619-b7b7f300-9b56-11ea-9902-9debba3f3ff0.png)

The displayed message is a little confusing, however it does sum to the correct number when rolled with negative modifiers.
