### ISSUE TITLE
!add having error after using !set

### ISSUE THREAD

**Issue by shseah601** [JohnWhy/DnD-Discord-Bot#17]
when i use !set currenthp 20, i wanna delete 5 hp by using !del current hp 5, the bot response with 'An error occurred, improper parameters'. after using !set im only able to use !set for the attribute.

**Comment by shseah601** [comment]
i suspect the !set is only set the attribute to string instead of integer or any numeric type of data. Is there any way to set the attribute to a number instead of string?

**Comment by JohnWhy** [comment]
If the input is a number, then it should default to an int, it doesn't appear to be doing that so I will look and make sure that wasn't broken somehow.  Thanks for the report.

**Comment by JohnWhy** [comment]
Bugfix attempted.
