### ISSUE TITLE
The createprof command is not working

### ISSUE THREAD

**Issue by JohnWhy** [JohnWhy/DnD-Discord-Bot#18]
The createprof command is not working

_Originally posted by @draco25812 in https://github.com/JohnWhy/DnD-Discord-Bot/issues/2#issuecomment-478872884_

This is an intermittent issue with no root cause found.  Investigation into the bug is ongoing, likely the entire create character is going to be rewritten for custom character creation.  If you experience this issue contact me with the exact stats you are trying to input and race, class, & background etc. so I can attempt to recreate it.

**Comment by amerald9748** [comment]
!createprof command not working for grung sorcerer(10 30 10 25 20 15) with archeologist background.
Stuck in character creation.

**Comment by JustCallMeDead** [comment]
!createprof wasnt working for my Dragonborn Paladin  (31  24   28 
29 19 22) with knight of the order background and i tried to get athletics and intimidation

**Comment by JohnWhy** [comment]
This is fixed, a catch has been added on !createstats that prevents you from using a stat over 20.  This was the culprit.

**Comment by CapitalistToast** [comment]
!createprof isn't working for Kobold Ranger (12 14 9 11 10 6) Outlander background trying to get Perception and Stealth
