### ISSUE TITLE
Can't make custom spells or cantrips

### ISSUE THREAD

**Issue by Halpmeplzmaybe** [JohnWhy/DnD-Discord-Bot#19]
My homebrew D&D group and I wanted to make a spell (for this scenario called "X"), how would I make a custom spell called "X" into my list of spells? If impossible, can you please make that a thing soon, please?

**Comment by JohnWhy** [comment]
`!add spells Custom Spell` is what you need.  You can give the Spells / Cantrips fields to put whatever you want in them.  Just make note of whatever the custom spell does.  This will be built upon with DMTools later.
