### ISSUE TITLE
Bot slowdowns & spam servers

### ISSUE THREAD

**Issue by JohnWhy** [JohnWhy/DnD-Discord-Bot#2]
Quick comment on when the bot isn't responding right away; Basically I've noticed an influx in "bot spam servers" as I call them.  I'm not sure their exact purpose, but to me, it looks like they only serve to slow bots down and spam them with requests to try and crash them.  Over the course of the past year (has it been that long?) I've dealt with 6 of them, sometimes the same one multiple times.  I've reported these bot spam servers to discord, but due to confidentiality they don't get back to me.  Last night, another bot spam server attacked D&D Bot, I was informed by users that the bot was acting extremely slow, I checked the logs, and saw a server spamming hundreds of requests a second.  In fact, it was a server I had previously reported.  Now this could mean one of two things.  Either discord isn't doing anything about these malicious servers, or they're being remade faster than discord can remove them.  Regardless, it's forced me to focus more time on developing preventative measures so that the bot will automatically leave a server that is spamming it.  If you notice any abnormal slowdowns, don't hesitate to get in touch with me on the support discord, and I'll look into the issue.  Thanks for your patience and continued support.

**Comment by JohnWhy** [comment]
This issue has been fixed, and should no longer be affecting user experience, if you experience bot slowdowns get in touch with me

**Comment by draco25812** [comment]
The createprof command is not working
