### ISSUE TITLE
!stats not working

### ISSUE THREAD

**Issue by RetirementNoir** [JohnWhy/DnD-Discord-Bot#21]
Hello,
I've just stated using DnD-Discord-Bot and am having a great time with it. The character creation process was extremely easy and the whole system is pretty intuitive.
I am, however, having trouble getting !stats and !stat ch to work while !stat eq !stat sp and !stat skill are all working. 
Any help or guidance would be much appreciated.
Thank you!

**Comment by RetirementNoir** [comment]
I fixed it by deleting and remaking the character.

**Comment by JohnWhy** [comment]
Sorry for the delayed response to this, deleting & remaking is generally the best way to fix issues like this.  Something must have been invalid in the character sheet portion of !stats which caused it to not display.  I've generally seen this more commonly on !stats eq but I'll make sure more fail safes are implemented.
