### ISSUE TITLE
!createrace not doing a damn thing

### ISSUE THREAD

**Issue by FenGryn** [JohnWhy/DnD-Discord-Bot#22]
I'm trying to create my character, but I can't seem to get a response from "!createrace custom" I can't get a response from "!createrace <custom race name>" I can't get a response from "!createrace <number boyond the options>"  I'm seriously getting frustrated, getting an error or something would be better than no response at all.

**Comment by JohnWhy** [comment]
The input for !createrace is looking for an integer value between 0 and 47.  Currently there is no "custom" race/background/class.  If you want to make a custom race/background/class, pick one that is close to what your custom component is, then add/remove the necessary stats, items, equipment, etc.  The !createcharacter process will be improved upon at a later date.
