### ISSUE TITLE
EQUIPMENT & FEATS Custom edits/change

### ISSUE THREAD

**Issue by shootingstarsungie** [JohnWhy/DnD-Discord-Bot#24]
I am able to change traits such as appearance and race in other menus, but Equipments and Feats has been giving me errors when I try to change certain Fields in that section of the sheet. I have included a screenshot to demonstrate what I mean.
![Screen Shot 2019-06-29 at 4 38 50 PM](https://user-images.githubusercontent.com/52359764/60389241-6a3d1e00-9a8c-11e9-92d8-07266bd08c80.png)

**Comment by shootingstarsungie** [comment]
So I was able to figure it out, but its not very clear that you're supposed to use !add and !del. My suggestion is making it clearer that this is how you alter those fields!

**Comment by JohnWhy** [comment]
I'll look into modifying these commands to give better feedback on improper parameter entry.  However due to the nature of how this is coded that may be difficult.
