### ISSUE TITLE
Feature Request: Store rolls

### ISSUE THREAD

**Issue by Majortom805** [JohnWhy/DnD-Discord-Bot#25]
So the idea would add something like this
!r initiative: Tells the bot to rolls a d20 and add dex mod from your character
!r attack Longbow: Tells the bot to roll a d20, check for proficiency in longbow, if_yes add to roll, add dex modifier
!r damage Longbow: Tells bot to roll damage for longbow, adds dex automatically.

Basically using the !add Attacks Longbow, you would have to either program all the weapons into the database and the bot would know the dice, versatility, finesse etc. Or you could have new commands.
!add attacks [weaponname] [proficient] [usingdex] [damagedie]
ex. !add longbow yes yes 1d8
ex. !add greatsword yes no 2d6
ex. !add improvised weapon no no 1

**Comment by JohnWhy** [comment]
Once the database for items is finished I can look into this as an addition.

**Comment by JohnWhy** [comment]
Won't be implemented.  Making changes that should make this obsolete.  Use `!search help`
