### ISSUE TITLE
Roll Prefix bug

### ISSUE THREAD

**Issue by Pheloraq** [JohnWhy/DnD-Discord-Bot#26]
Hello I changed the prefix to !dnd, !m, !dd etc and it works with other commands such as listchar and changeprefix but it doesnt work on doing roll. So I changed it back to its origianl prefix and it works fine with that then I found out that the rolls work alright when I made the prefix = rather than !(something).

**Comment by JohnWhy** [comment]
Prefixes with characters can break the roll command due to how it parses the information received.  Prefixes like `$%^&*_` etc should not have any issue, but prefixes containing `+` or `-` or characters might break it.
