### ISSUE TITLE
New ability for dms

### ISSUE THREAD

**Issue by Pumpkinbros** [JohnWhy/DnD-Discord-Bot#27]
The ablility for the dms of the server/game to be able to edit the others player sheets, you know to change their XP, and health, so the players themselves don't have to change these stats, it would make it so the dms can immerse the players a bit more, so the games aren't filled with commands and such, you made such an amazing bot, thank you

**Comment by JohnWhy** [comment]
DM Tools are being worked on and planned.  `!givechar` and `!get_random_monster` have been implemented as the first steps towards this.
