### ISSUE TITLE
Problem with complex rolls

### ISSUE THREAD

**Issue by Brendon003214** [JohnWhy/DnD-Discord-Bot#28]
We tried to roll stats using '!r4d6d1'. As it tuned out, the bot was not only unable to comprehend the 'd1' at the and, but it didn't even give any reflection or error message, just went on rolling 4d6.
I think it would be beneficial to add this feature, especially to make rolling stats easier.

**Comment by ChickenMobile** [comment]
The commands are: kl# - keep lowest, kh# - keep highest
So if you want to drop the lowest number use: !r4d6 kh3
