### ISSUE TITLE
!r command needs some changes

### ISSUE THREAD

**Issue by Sempiternity87** [JohnWhy/DnD-Discord-Bot#3]
In the example for this command, it says that you can use "!r3d4 -5" to roll 3d4 and subtract 5 from **each** roll. I can't think of any reason why this would be useful.

When I used it, I get Sum: -8 (-4, -1, -3) but was expecting something along the lines of Sum: 2 (1+4+2=7-5). It would be far more useful to have the five be subtracted from the result. That way, if needed, you can still have a number subtracted from each die by using "!r3d4 -15".

Also, it would be great to have an ability to drop some dice from the roll before totaling. This would be useful for rolling stats. "!r4d6kh3" would roll four d6, and keep the highest three dice, then sum those numbers together. Also, having a "kl#" for keeping lowest dice would be good too. This is useful for rolling advantage/disadvantage as well (!r2d20kh1 or !r2d20kl1).

**Comment by JohnWhy** [comment]
I'll look into this one and update the command when I get a chance.  I'll try to get it done before 1.3

**Comment by JohnWhy** [comment]
This has been updated and will work in 1.2.1 when it's released
