### ISSUE TITLE
prefix doesnt work after changing it

### ISSUE THREAD

**Issue by dndbotfail** [JohnWhy/DnD-Discord-Bot#34]
i changed the bot's prefix to \test and it doesnt work, cant revert it back either.
i noticed entering \\ in chat returns a single \, i guess discord got its own use for that character?

**Comment by JohnWhy** [comment]
Some prefixes do not work with the bot due to the way certain commands are parsed.  Updated the !changeprefix command to give recommendations and only allow certain prefixes to be entered.
