### ISSUE TITLE
Bot doesn't respond properly to commands 

### ISSUE THREAD

**Issue by MasterAlina0485** [JohnWhy/DnD-Discord-Bot#35]
None of the commands work except !help, !bugreport and !changelog. !r with any of the sub commands for rolling dice gets me this in the screenshot: 
<img width="699" alt="Screen Shot 2019-10-14 at 23 46 34" src="https://user-images.githubusercontent.com/31673974/66952160-e7c37480-f010-11e9-8924-1d23bfedec8c.png">

It seems to be a problem in only one specific server, all other servers with the bot work.

**Comment by JohnWhy** [comment]
Permissions issue, make sure the bot has the ability to send embed links

![image](https://user-images.githubusercontent.com/8998268/82736169-84f83100-9cf5-11ea-81ae-df8b8813d9fc.png)
