### ISSUE TITLE
Dex dice modifiers?

### ISSUE THREAD

**Issue by Gwenniffer318** [JohnWhy/DnD-Discord-Bot#37]
not necessarily an issue but more of a question or suggestion. 
so the base roll command is !r1d20 for example, i think it would be nice or easier to be able to stack commands like if i wanted to roll a d20 with a d4 for a modifier (!r1d20+1d4) could be a possible command i think, not too sure how coding works. love the bot tho, also heads up cant find @AmericanLegend#6969 on discord btw.

**Comment by JohnWhy** [comment]
Duplicate request.  Known requested enhancement.
