### ISSUE TITLE
Cannot change the NumSpells or NumCantrips values

### ISSUE THREAD

**Issue by ChickenMobile** [JohnWhy/DnD-Discord-Bot#39]
The NumSpells and NumCantrips values cannot be changed under Spells & Cantrips.
Using `!add/!del NumSpells 1` does not increase or decrease the number
Using `!set NumSpells 1` comes up with an error. 

If it does work: the format is not obvious.

**Comment by JohnWhy** [comment]
Updated in latest version, should be solved.
