### ISSUE TITLE
Feature Enhancement: Roll as character / Display user's nickname instead of username.

### ISSUE THREAD

**Issue by aprostko** [JohnWhy/DnD-Discord-Bot#40]
Allow rolling to roll as a character so it shows up as a roll coming from that character instead (or in addition to that user). Allow the roll to use the user's nickname instead of their username since most players recognize a player by their nickname since that is what is displayed within chat channels when they are communicating.

**Comment by JohnWhy** [comment]
I will add character name & Discord name to the message, that way everyone is pleased.  Planned for v1.3.1

**Comment by JohnWhy** [comment]
Added in dev for next update.
![image](https://user-images.githubusercontent.com/8998268/82766031-9884c400-9de9-11ea-9cea-366c01682906.png)
