### ISSUE TITLE
D&D bot command error !stat eq doesn't work

### ISSUE THREAD

**Issue by ooofXD** [JohnWhy/DnD-Discord-Bot#42]
When you'reemakeing a character with the 
@D&D_Bot there is a command; !stat eq which should show you a list of things for you're character but the command doesn't workin fact the bot doesn't respond at all. I don't have issues with any other command  i'ts annoying need help to figure this out

**Comment by JohnWhy** [comment]
This issue occurs when the page has too much information on it, discord has a character limit of 2000 and if the page has more than 2000 characters it won't display.  I will work on a patch for this.

**Comment by JohnWhy** [comment]
Patch ready for 1.6
