### ISSUE TITLE
!stat eq doesn't work

### ISSUE THREAD

**Issue by ooofXD** [JohnWhy/DnD-Discord-Bot#43]
Bot won't respond to this command (i use #stat eq since i've changed the prefix to # no luck)

All other commands work not this one

**Comment by ooofXD** [comment]
Couldn't fix had to delete and redo my character entirely sucks

**Comment by JohnWhy** [comment]
Discord has a 2000 character limit, if the embed has more than 2000 characters it cannot be displayed.  Known issue.
