### ISSUE TITLE
Feature Request: Roll multiple dice types

### ISSUE THREAD

**Issue by Culture20** [JohnWhy/DnD-Discord-Bot#50]
Useful for guidance, extra damage from hunter's mark, battlemaster technique extra damage and many other rolls which add different dice to existing rolls (and keep the same damage type, so summing them makes sense)

paraphrased new-feature Expected behavior:
!r1d20 + 1d4 => 1d20=15, 1d4=3 Sum=18
!r2d20kl1 + 1d4 => 1d20=2, 1d20=19, lowest roll(s)=2, 1d4=2 Sum=4
paraphrased current Actual behavior:
!r1d20 + 1d4 => 1d20=15 +1 Sum=16
!r2d20kl1 + 1d4 => 1d20=2, 1d20=19,1 lowest roll(s)=2 +1 Sum=3

**Comment by JohnWhy** [comment]
Would require major re-write of the roll dice script.  Not planned currently, but can be looked into in the future.
