### ISSUE TITLE
Feature Recommendation: Commands

### ISSUE THREAD

**Issue by Athrislor** [JohnWhy/DnD-Discord-Bot#52]
I would love to see a command that pulls up what the other commands are because I constantly forget the other commands or the number of commands I actually have access to. It would be nice to see the commands by typing in something simple like !commands, or !clist, or something along those lines. Just a suggestion, as I am a new user of the bot as well.

**Comment by JohnWhy** [comment]
Current recommendation is to use the Github page, !help will link you to it.

There's too many commands to easily display them all and explain.
