### ISSUE TITLE
Feture Request: Crit damage multiplier

### ISSUE THREAD

**Issue by TuVieja64** [JohnWhy/DnD-Discord-Bot#53]
It would be good to have a modifier to the dice wich multiplies the result i.e.

!r1d8*2+5 => Roll #1: 3, MULT = 3*2 = 6, SUM = 6 + 5 = 11

This would merely be quality of life, not a needed thing, but could be useful.

**Comment by JohnWhy** [comment]
Crit damage is done by rolling twice as many dice per the Handbook.  If a critical damage is being applied, instead of `!r1d8` the user should do `!r2d8`.
