### ISSUE TITLE
BEST BOTS EVER

### ISSUE THREAD

**Issue by vyntnah** [JohnWhy/DnD-Discord-Bot#58]

**Comment by vyntnah** [comment]
YAYAYAYAYAY I LUV DIS BOT BUT LEMME ROLL 69 DICE

**Comment by JohnWhy** [comment]
Appreciate the feedback! Dice rolling is limited to 25 to prevent the bot from spamming a channel with unneeded information.  If there's a legitimate need for 69 dice to be rolled in D&D by all means let me know!

Thanks
