### ISSUE TITLE
Not Issue but Feature for spells

### ISSUE THREAD

**Issue by Vicguin65** [JohnWhy/DnD-Discord-Bot#6]
Could you add a command for spells? My dnd group runs into the issue of not knowing every single detail of a spell. I wonder if there was a command like !spell Cure Wounds. And the bot would describe the spell like the handbook.

**Comment by JohnWhy** [comment]
This is a planned feature in the coming updates.  An entire 5E database is being worked on that will allow you to search items, spells, armor, and other equipment and get a description of each.

Here is a rough preview of how that will work

![m8cbksi](https://user-images.githubusercontent.com/8998268/52016279-1d8bf180-24b2-11e9-83ec-0fe44f4905e3.png)

**Comment by JohnWhy** [comment]
Implemented, use `!search help`
