### ISSUE TITLE
Feature request: comments on roll

### ISSUE THREAD

**Issue by maubernardi** [JohnWhy/DnD-Discord-Bot#62]
Hi!
I think that this is one of the best D&D bots ever. But I think it could be useful if you can add a comment after the roll command, something like 
!r 1d20+6 !XXXXX
So the output could be 
1d20 rolls by <charname> for <XXXXX>
Thank you!

**Comment by JohnWhy** [comment]
I'll add this for 1.6, seems like an easy enough request under the new / framework.

**Comment by JohnWhy** [comment]
Completed for 1.6 
![jRg8Uws](https://github.com/JohnWhy/DnD-Discord-Bot/assets/8998268/4b878864-2796-4760-b24b-1a9118bb4ec6)
