### ISSUE TITLE
Cannot use the !r command on a certain channel

### ISSUE THREAD

**Issue by SharkieDaShark** [JohnWhy/DnD-Discord-Bot#63]
The !r command does not work on a certain channel. The other commands work for instance !createcharacter and even !flipcoin. When using the !r command it gives the error response: 

Something went wrong!
For help with the >r command, see this guide.

**Comment by JohnWhy** [comment]
This is likely an embed issue.  Make sure the bot has permission to send embedded links in the channel where it's failing.
