### ISSUE TITLE
!createstats Str Dex Con Int Wis Cha not working

### ISSUE THREAD

**Issue by dwaynamay** [JohnWhy/DnD-Discord-Bot#66]
I'm using this command in PM to bot. Results in no reply.

**Comment by Rene707** [comment]
I had an issue too, and found that it only works if you set all 6 at once (For example: !createstats 10 12 13 15 15 18)
Try this and if it doesn't work, then there is something wrong

**Comment by JohnWhy** [comment]
Closed, solution given.  /createstats requires all 6 stats to be entered at the same time so the bot can calculate the next step properly.
