### ISSUE TITLE
[request] Ability for a DM to edit a player's character sheet

### ISSUE THREAD

**Issue by Wagasani** [JohnWhy/DnD-Discord-Bot#68]
I am a DM to a few new players and I think it would be beneficial if I were able to make edits to a character's sheet. It would be a lot easier if I were able to just say `<!del CurrentHP 5 @Player>` rather than have them type in this command in the heat of battle.

**Comment by JohnWhy** [comment]
Planned but again going to take a while due to data management issues on the bot.
