### ISSUE TITLE
Feature request - add rolls

### ISSUE THREAD

**Issue by jenthura** [JohnWhy/DnD-Discord-Bot#69]
It would be nice to roll several dice, like an attack and damage dice all together. Maybe something like:
!r1d20+1d10
or
!r1d20+!r1d10

**Comment by Schop0** [comment]
I'd like to expand on this by requesting basic math such as !r1d20 + dex + 3 + !r1d4 + 7 + etcetera.

**Comment by JohnWhy** [comment]
!r1d20+DEX should be the command you're looking for to add in modifiers, however parsing multiple dice rolls at once is something i'll have to look into.  The entire command structure needs to be rewritten due to a discord change.
