### ISSUE TITLE
Prefix Bug

### ISSUE THREAD

**Issue by JohnWhy** [JohnWhy/DnD-Discord-Bot#7]
Currently custom prefixes are breaking.  I'm working on finding the root cause.  Until then they may be wiped frequently.

**Comment by JohnWhy** [comment]
This has been fixed, if you still have your prefix not working, reset it using `!changeprefix` so that it can be added to the new db which has been created to handle prefixes.

**Comment by Pheloraq** [comment]
Hello I changed the prefix and it works with other commands such as listchar and changeprefix but it doesnt work on doing roll. so i changed it back to its origianl prefix and it works fine with that.

**Comment by JohnWhy** [comment]
If the prefix was + or - it breaks the command, there is a warning in place when you try to change your prefix to either of these.
