### ISSUE TITLE
Prefix change cause no response from bot

### ISSUE THREAD

**Issue by andyfan1** [JohnWhy/DnD-Discord-Bot#71]
Changing the prefix makes the bot unusable except for help and change prefix.

**Comment by UsainVolt2941** [comment]
please fix this, the prefix interferes with the mee6 prefix, and we can't mute mee6, since it has administrator

**Comment by JohnWhy** [comment]
Use !prefixreset to force the prefix back to the original.  This is hard coded to work with "!" prefix. 

!changeprefix has issues with + and - as prefixes due to the parsing of the roll command, this is subject to change in the future.
