### ISSUE TITLE
[Feature Idea] Rerolling

### ISSUE THREAD

**Issue by KaiZano** [JohnWhy/DnD-Discord-Bot#72]
A feature to allow the bot to reroll when a dice gets a 1 (example: !r4d6rr(1,3,4)kh3, It would roll 4d6 then reroll any 1 3 or 4s then keep the highest 3.

**Comment by JohnWhy** [comment]
Due to upcoming discord changes this entire feature is likely to be remade, likely without kh/kl commands and simplified heavily to just rolling X amount of dice.  Expansions on this aren't likely.
