### ISSUE TITLE
Proficiency bonus is buggy

### ISSUE THREAD

**Issue by wrice6** [JohnWhy/DnD-Discord-Bot#74]
It looks like the proficiency bonus doesn't change for higher levels. The proficiency bonus at level 5 is +3, but it shows as +2. Even when I changed it manually, it shows as a +2, and it won't change the specific skills' bonuses either. Like my insight is +5 but shows as +4, even when I changed the bonus using the command to change the proficiency bonus manually.

**Comment by JohnWhy** [comment]
Level up is not implemented, prof bonuses would need to be manually adjusted.
