### ISSUE TITLE
Equipment Stats Not Working

### ISSUE THREAD

**Issue by pkyoko** [JohnWhy/DnD-Discord-Bot#77]
Uh, I was creating a character and writing the backstory in segments, and now it won't let me access my equipment status. I've tried deleting some segments or deleting all of it but it just keeps saying i have improper parameters. What am I doing wrong? I spent super long setting this character up and it would be a shame if i had to delete and restart all that work. Please get back to me as soon as possible.

**Comment by JohnWhy** [comment]
Apologies for not getting back right away.  This likely is a result of having too much equipment but I can't say for sure.  Equipment/Backstories are being re-worked for 1.6 and will display separately to alleviate these issues.
