### ISSUE TITLE
We need a 1d2

### ISSUE THREAD

**Issue by Arctic0Reaper** [JohnWhy/DnD-Discord-Bot#78]
I know you have the coin flip, but we need a d2 too. Me and my friends play dnd and we were looking for a bot, but they skipped over this one purely for the fact. I thought it was cool, but they’re not interested unless it out can roll a d2.

**Comment by xthejuggernaut** [comment]
Bro what? I've never even seen a 1d2 in real life unless your just talking about the coins that have 1 and 2 on them. What's so hard about heads or tails?

**Comment by JohnWhy** [comment]
1d2 does not exist, flip coin is all that should be needed and is outside the scope of this project
