### ISSUE TITLE
Changling Race

### ISSUE THREAD

**Issue by Rafiki6392** [JohnWhy/DnD-Discord-Bot#8]
Create Changling Race

**Comment by JohnWhy** [comment]
Hi, can you link me to some official / widely accepted D&D 5E documentation for the specific player-character race you want added?  Thanks.

**Comment by Viyomon** [comment]
Umm I'm not this person, but is this source okay? https://www.dndbeyond.com/races/changeling

**Comment by JohnWhy** [comment]
Changeling_INT and Changeling_DEX will be added in the next update.  INT and DEX refer to the modifier choice changelings have on creation.
