### ISSUE TITLE
Turning channels into worlds - idea request

### ISSUE THREAD

**Issue by The-Critika** [JohnWhy/DnD-Discord-Bot#80]
It would be nice if we could set a channel as a certain "map". It could have a custom image and a description. The users could send a certain command and it can pop up for the people who want to rp in it.

**Comment by JohnWhy** [comment]
Unlikely to happen, DM Tools will enable DMs to have campaigns where they can set maps and such, adding characters to a campaign will allow players to interact in various ways.  This is planned for a future release.
