### ISSUE TITLE
New Feature: add rolling with stats

### ISSUE THREAD

**Issue by theTabaxi** [JohnWhy/DnD-Discord-Bot#83]
Just as the name suggests. Maybe add a feature where you can use the stats, like skills and saves, from your current character. Shouldn't be too hard I guess, I know a bit of coding so I know you can add variables to equasions. This would make the bot a lot easier to use, as you don't really need to look up your stats

**Comment by JohnWhy** [comment]
This should already be possible:
https://github.com/JohnWhy/DnD-Discord-Bot/blob/master/Rolling%20Guide.md

!r2d20kh1 + acrobatics - This will roll 2 20 sided dice, and keep the highest one, then add in the acrobatics skill to that highest roll.
!r1d20 + Acrobatics - This will roll 1 20 sided dice and add in your Acrobatics. (case insensitive)
!r1d20 + str - This will roll 1 20 sided dice and add in your Strength modifier. (case insensitive)
