### ISSUE TITLE
Fighter has wrong Saving Throws and max HP

### ISSUE THREAD

**Issue by Baal-Pheor** [JohnWhy/DnD-Discord-Bot#85]
I have created fighter character but he has wisdom and intelligence saving throws instead of strength and constitution. Also max HP isn't takes into account constitution modifier or fighter has wrong HP dice (10 HP fighter  with 14 constitution).

**Comment by JohnWhy** [comment]
User error, the SavingThrows for Fighter are properly set to Str and Con.  Make sure you didn't accidentally select a different class on character creation.
