### ISSUE TITLE
Appearance Bug

### ISSUE THREAD

**Issue by piepertuba** [JohnWhy/DnD-Discord-Bot#9]
When trying to change the appearance of the character it will not change from the default and the bot will not trigger.  Copying the example from the command information page doesn't yield results either.

**Comment by JohnWhy** [comment]
This will be remedied in the next hotfix.  The issue is with the command's alias.  It was updated to !appear when switched to `bot commands` framework and I forgot to give it the alias `appearance`.  If you want to edit appearance similar to the example, use `!appear`.

**Comment by JohnWhy** [comment]
This has been fixed.
